import { task } from "@trigger.dev/sdk";
import pg from "pg";
import { publicAccessRecoveryAction } from "../src/deployment-recovery-rules.mjs";
import { assertSafeWorkloadRedirect, assertSafeWorkloadUrl, publicAccessRequestInit } from "../src/workload-http.mjs";

const { Client } = pg;
const API = "https://api.vercel.com";
const BROWSER_UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36";

function teamQuery(){const teamId=process.env.VERCEL_TEAM_ID;return teamId?`?teamId=${encodeURIComponent(teamId)}`:""}
async function vercelRequest(path:string,options:RequestInit={}){if(!process.env.VERCEL_TOKEN)throw new Error("Missing VERCEL_TOKEN");const response=await fetch(`${API}${path}`,{...options,headers:{Authorization:`Bearer ${process.env.VERCEL_TOKEN}`,"Content-Type":"application/json",...(options.headers??{})}});const text=await response.text();let body:any=null;if(text){try{body=JSON.parse(text)}catch{body=null}}if(!response.ok)throw new Error(`Vercel API ${response.status} ${response.statusText}`);return body}
function isVercelAuthRedirect(location:string|null){if(!location)return false;try{const u=new URL(location);return u.hostname==="vercel.com"||u.hostname.endsWith(".vercel.com")}catch{return /vercel\.com/i.test(location)}}
async function anonymousCheck(url:string){assertSafeWorkloadUrl(url);const started=Date.now();const response=await fetch(url,publicAccessRequestInit({signal:AbortSignal.timeout(8000),userAgent:BROWSER_UA}));const latencyMs=Date.now()-started;const location=response.headers.get("location");let redirectUnsafe=false;if(location){try{assertSafeWorkloadRedirect(location,url)}catch{redirectUnsafe=true}}const vercelAuthRedirect=isVercelAuthRedirect(location);const publiclyReachable=!redirectUnsafe&&!vercelAuthRedirect&&response.status>=200&&response.status<400;try{await response.body?.cancel()}catch{}return{httpStatus:response.status,latencyMs,location,vercelAuthRedirect,redirectUnsafe,publiclyReachable}}

export const configurePublicAccess=task({id:"ssc-control-plane-configure-public-access",retry:{maxAttempts:2,minTimeoutInMs:2000,maxTimeoutInMs:8000,factor:2,randomize:false},run:async(payload:{deploymentId:string})=>{
 if(!process.env.DATABASE_URL)throw new Error("Missing DATABASE_URL");const db=new Client({connectionString:process.env.DATABASE_URL});await db.connect();
 try{
  const result=await db.query(`SELECT d.id,d.status,d.live_url,rt.provider,rt.provider_project_id,b.provider_deployment_id,b.provider_deployment_url FROM deployments d JOIN app_runtimes rt ON rt.app_id=d.app_id JOIN deployment_builds b ON b.deployment_id=d.id WHERE d.id=$1`,[payload.deploymentId]);
  if(result.rowCount===0)throw new Error(`Deployment/runtime/build not found: ${payload.deploymentId}`);const row=result.rows[0];if(row.provider!=="vercel")throw new Error(`Unsupported runtime provider: ${row.provider}`);const action=publicAccessRecoveryAction(row.status);if(action.action==="terminal-noop")return{result:"NODE_04_18_TERMINAL_NOOP",deploymentId:payload.deploymentId,status:row.status,publiclyReachable:false,responseBodyStored:false,target:"production"};if(action.action==="live-replay-noop")return{result:"NODE_04_18_PUBLIC_ACCESS_REPLAY_NOOP",deploymentId:payload.deploymentId,providerProjectId:row.provider_project_id,providerDeploymentId:row.provider_deployment_id,checkUrl:row.live_url,publiclyReachable:true,status:"LIVE",responseBodyStored:false,target:"production"};if(action.action!=="verify-public-access")throw new Error(`Production public verification requires HEALTH_CHECKING or LIVE; current status is ${row.status}`);
  const providerDeployment=await vercelRequest(`/v13/deployments/${encodeURIComponent(row.provider_deployment_id)}${teamQuery()}`);
  if(providerDeployment?.target!=="production")throw new Error(`Provider deployment is not production-targeted; target is ${providerDeployment?.target??"null"}`);
  if((providerDeployment?.readyState??providerDeployment?.state)!=="READY")throw new Error(`Provider production deployment is not READY`);
  const project=await vercelRequest(`/v9/projects/${encodeURIComponent(row.provider_project_id)}${teamQuery()}`);
  const productionHost=(Array.isArray(providerDeployment?.alias)&&providerDeployment.alias.find((a:string)=>a===`${project.name}.vercel.app`))||(Array.isArray(project?.domains)&&project.domains.find((d:string)=>d===`${project.name}.vercel.app`))||`${project.name}.vercel.app`;
  const checkUrl=`https://${productionHost}`;const checked=await anonymousCheck(checkUrl);const redirectLocationHost=checked.location?(()=>{try{return new URL(checked.location,checkUrl).hostname}catch{return null}})():null;
  if(checked.publiclyReachable){await db.query("BEGIN");try{await db.query(`UPDATE deployments SET status='LIVE',live_url=$1,error_code=NULL,error_message=NULL,finished_at=now(),updated_at=now() WHERE id=$2 AND status='HEALTH_CHECKING'`,[checkUrl,payload.deploymentId]);await db.query(`INSERT INTO deployment_events (deployment_id,from_status,to_status,event_type,message,metadata) VALUES ($1,'HEALTH_CHECKING','LIVE','PUBLIC_ACCESS_VERIFIED','Healthy production deployment is publicly reachable',$2::jsonb)`,[payload.deploymentId,JSON.stringify({checkUrl,httpStatus:checked.httpStatus,latencyMs:checked.latencyMs,redirectLocationHost,vercelAuthRedirect:checked.vercelAuthRedirect,redirectUnsafe:checked.redirectUnsafe,responseBodyStored:false,providerDeploymentId:row.provider_deployment_id,target:"production"})]);await db.query("COMMIT")}catch(error){await db.query("ROLLBACK");throw error}}
  else{await db.query(`INSERT INTO deployment_events (deployment_id,from_status,to_status,event_type,message,metadata) VALUES ($1,$2,$2,'PUBLIC_ACCESS_BLOCKED','Production deployment is not publicly reachable without provider authentication',$3::jsonb)`,[payload.deploymentId,row.status,JSON.stringify({checkUrl,httpStatus:checked.httpStatus,latencyMs:checked.latencyMs,redirectLocationHost,vercelAuthRedirect:checked.vercelAuthRedirect,redirectUnsafe:checked.redirectUnsafe,responseBodyStored:false})])}
  return{result:checked.publiclyReachable?"NODE_04_11_PUBLIC_ACCESS_VERIFIED":"NODE_04_11_PUBLIC_ACCESS_BLOCKED",deploymentId:payload.deploymentId,providerProjectId:row.provider_project_id,providerDeploymentId:row.provider_deployment_id,checkUrl,httpStatus:checked.httpStatus,latencyMs:checked.latencyMs,redirectLocationHost,vercelAuthRedirect:checked.vercelAuthRedirect,redirectUnsafe:checked.redirectUnsafe,publiclyReachable:checked.publiclyReachable,status:checked.publiclyReachable?"LIVE":row.status,responseBodyStored:false,target:"production"};
 }finally{await db.end()}
}});
