import { task, tasks, wait } from "@trigger.dev/sdk";
import pg from "pg";
import {
  INTERNAL_RESUME_ACCEPTANCE_POINT_AFTER_ENV,
  maybeInterruptInternalResumeAcceptance,
} from "../src/internal-resume-acceptance-hook.mjs";
import { recordRemoteBuildContainment } from "../src/vercel-deployment-cancellation.mjs";
const { Client }=pg; const BUILD_POLL_SECONDS=15; const HEALTH_RETRY_SECONDS=10;
async function deploymentSnapshot(deploymentId:string){if(!process.env.DATABASE_URL)throw new Error("Missing DATABASE_URL");const db=new Client({connectionString:process.env.DATABASE_URL});await db.connect();try{const result=await db.query(`SELECT d.id,d.workspace_id,d.app_id,d.status,d.error_code,d.error_message,b.provider_deployment_id,b.status AS build_status,b.created_at AS build_created_at,COALESCE(p.max_build_minutes,15) AS max_build_minutes,COALESCE(p.max_health_attempts,3) AS max_health_attempts FROM deployments d LEFT JOIN deployment_builds b ON b.deployment_id=d.id LEFT JOIN app_resource_policies p ON p.app_id=d.app_id WHERE d.id=$1`,[deploymentId]);if(result.rowCount===0)throw new Error(`Deployment not found: ${deploymentId}`);return result.rows[0]}finally{await db.end()}}
function buildElapsedMs(snapshot:any){const started=snapshot.build_created_at?new Date(snapshot.build_created_at).getTime():0;return started?Math.max(0,Date.now()-started):0}
async function containTimedOutBuild(deploymentId:string){if(!process.env.DATABASE_URL)throw new Error("Missing DATABASE_URL");const db=new Client({connectionString:process.env.DATABASE_URL});await db.connect();try{const result=await db.query(`SELECT d.status,d.error_code,b.provider_deployment_id FROM deployments d LEFT JOIN deployment_builds b ON b.deployment_id=d.id WHERE d.id=$1`,[deploymentId]);if(result.rowCount===0)throw new Error(`Deployment not found: ${deploymentId}`);const row=result.rows[0];if(row.status==="FAILED"&&row.error_code==="BUILD_TIMEOUT"&&row.provider_deployment_id)return recordRemoteBuildContainment(db,{deploymentId,fromStatus:"FAILED",providerDeploymentId:row.provider_deployment_id,reason:"BUILD_TIMEOUT"});return null}finally{await db.end()}}
async function failBuildTimeout(deploymentId:string,maxBuildMinutes:number){if(!process.env.DATABASE_URL)throw new Error("Missing DATABASE_URL");const db=new Client({connectionString:process.env.DATABASE_URL});await db.connect();try{const reread=await db.query(`SELECT d.status,b.provider_deployment_id FROM deployments d LEFT JOIN deployment_builds b ON b.deployment_id=d.id WHERE d.id=$1`,[deploymentId]);if(reread.rowCount===0)throw new Error(`Deployment not found: ${deploymentId}`);const row=reread.rows[0];let containment:any=null;if(row.status==="BUILDING"&&row.provider_deployment_id){containment=await recordRemoteBuildContainment(db,{deploymentId,fromStatus:"BUILDING",providerDeploymentId:row.provider_deployment_id,reason:"BUILD_TIMEOUT"})}await db.query("BEGIN");try{const message=`Application build exceeded the ${maxBuildMinutes}-minute resource policy limit.`;const updated=await db.query(`UPDATE deployments SET status='FAILED',error_code='BUILD_TIMEOUT',error_message=$1,finished_at=now(),updated_at=now() WHERE id=$2 AND status='BUILDING' RETURNING id`,[message,deploymentId]);if(updated.rowCount===1){await db.query(`UPDATE deployment_builds SET status='POLICY_TIMEOUT',updated_at=now() WHERE deployment_id=$1`,[deploymentId]);await db.query(`INSERT INTO deployment_events (deployment_id,from_status,to_status,event_type,message,metadata) VALUES ($1,'BUILDING','FAILED','BUILD_TIMEOUT',$2,$3::jsonb)`,[deploymentId,message,JSON.stringify({maxBuildMinutes,remoteContainment:containment?.outcome??null})])}await db.query("COMMIT");return containment}catch(error){await db.query("ROLLBACK");throw error}}finally{await db.end()}}
async function child(id:string,deploymentId:string,label:string){const result=await tasks.triggerAndWait(id,{deploymentId});if(!result.ok)throw new Error(`${label} task failed`);return result.output as any}
export const orchestrateDeployment=task({id:"ssc-control-plane-orchestrate-deployment",retry:{maxAttempts:1},run:async(payload:{deploymentId:string})=>{
 let current=await deploymentSnapshot(payload.deploymentId);if(["LIVE","FAILED","DELETED"].includes(current.status)){const remoteContainment=await containTimedOutBuild(payload.deploymentId);return{result:"NODE_04_15_TERMINAL_NOOP",deploymentId:payload.deploymentId,status:current.status,errorCode:current.error_code,remoteContainment:remoteContainment?.outcome??null}};
 if(current.status==="ANALYZING"){await child("ssc-control-plane-prepare-build-input",payload.deploymentId,"Build input preparation");await child("ssc-control-plane-detect-env-requirements",payload.deploymentId,"Environment requirement detection");const envOutput=await child("ssc-control-plane-verify-env-requirements",payload.deploymentId,"Environment requirement verification");if(envOutput?.result==="NODE_04_17_ENV_CONFIGURATION_REQUIRED")return{result:"NODE_04_17_ENV_CONFIGURATION_REQUIRED",deploymentId:payload.deploymentId,status:"ANALYZING",missingKeys:envOutput.missingKeys,missingCount:envOutput.missingCount};const internalResumeAcceptance=await maybeInterruptInternalResumeAcceptance({deploymentId:payload.deploymentId,workspaceId:current.workspace_id,appId:current.app_id,status:"ANALYZING",point:INTERNAL_RESUME_ACCEPTANCE_POINT_AFTER_ENV});if(internalResumeAcceptance.interrupted)return{result:"UTPLAVA_INTERNAL_RESUME_ACCEPTANCE_INTERRUPTED",deploymentId:payload.deploymentId,status:"ANALYZING",point:internalResumeAcceptance.point};current=await deploymentSnapshot(payload.deploymentId)}
 if(current.status==="PROVISIONING"){const dbOutput=await child("ssc-control-plane-provision-database",payload.deploymentId,"Managed database reconciliation");if(["NODE_15R_12A_MANAGED_DATABASE_LIMIT_REACHED","NODE_15R_12A_DATABASE_CREATE_IN_FLIGHT","NODE_15R_12A_DATABASE_RECONCILIATION_REQUIRED","NODE_15R_12A_DATABASE_RECONCILIATION_AMBIGUOUS"].includes(dbOutput?.result))return{result:dbOutput.result,deploymentId:payload.deploymentId,status:"PROVISIONING",database:dbOutput};await child("ssc-control-plane-provision-runtime",payload.deploymentId,"Runtime reconciliation");current=await deploymentSnapshot(payload.deploymentId)}
 if(current.status==="BUILDING"&&!current.provider_deployment_id){const policyOutput=await child("ssc-control-plane-enforce-resource-policy",payload.deploymentId,"Resource policy");if(policyOutput?.allowed!==true)return{result:"NODE_04_15_POLICY_BLOCKED",deploymentId:payload.deploymentId,status:"BUILDING",policy:policyOutput};await child("ssc-control-plane-apply-runtime-env",payload.deploymentId,"Runtime environment reconciliation");const buildOutput=await child("ssc-control-plane-execute-build",payload.deploymentId,"Build execution");if(buildOutput?.result==="NODE_04_10_BLOCKED_EXTERNAL_QUOTA")return{result:"NODE_04_15_PROVIDER_BLOCKED",deploymentId:payload.deploymentId,status:"BUILDING",providerResult:buildOutput};if(buildOutput?.result==="NODE_15R_11_PROVIDER_OPERATION_LIMIT_REACHED")return{result:"NODE_15R_11_PROVIDER_OPERATION_LIMIT_REACHED",deploymentId:payload.deploymentId,status:"BUILDING",providerResult:buildOutput};if(["NODE_04_18_BUILD_RECOVERY_PENDING","NODE_04_18_BUILD_RECOVERY_AMBIGUOUS"].includes(buildOutput?.result))return{result:buildOutput.result,deploymentId:payload.deploymentId,status:"BUILDING",buildRecovery:buildOutput}}
 current=await deploymentSnapshot(payload.deploymentId);if(current.status==="BUILDING"&&current.provider_deployment_id){const buildDeadlineMs=Number(current.max_build_minutes)*60000;while(true){const out=await child("ssc-control-plane-reconcile-build",payload.deploymentId,"Build reconciliation");if(out?.result==="NODE_04_10_BUILD_VERIFIED")break;if(["NODE_04_10_BUILD_FAILED","NODE_04_10_SOURCE_MISMATCH"].includes(out?.result)){await child("ssc-control-plane-ingest-build-logs",payload.deploymentId,"Build log ingestion");const failed=await deploymentSnapshot(payload.deploymentId);return{result:"NODE_04_15_FAILED",deploymentId:payload.deploymentId,status:failed.status,errorCode:failed.error_code}}current=await deploymentSnapshot(payload.deploymentId);if(buildElapsedMs(current)>=buildDeadlineMs){await child("ssc-control-plane-ingest-build-logs",payload.deploymentId,"Build log ingestion");const containment=await failBuildTimeout(payload.deploymentId,Number(current.max_build_minutes));return{result:"NODE_04_15_BUILD_TIMEOUT",deploymentId:payload.deploymentId,status:"FAILED",errorCode:"BUILD_TIMEOUT",maxBuildMinutes:Number(current.max_build_minutes),remoteContainment:containment?.outcome??null}}await wait.for({seconds:BUILD_POLL_SECONDS})}await child("ssc-control-plane-ingest-build-logs",payload.deploymentId,"Build log ingestion")}
 current=await deploymentSnapshot(payload.deploymentId);if(current.status==="DEPLOYING"||current.status==="HEALTH_CHECKING"){while(true){const health=await child("ssc-control-plane-health-check",payload.deploymentId,"Health check");if(health?.result==="NODE_04_11_HEALTHY"){const access=await child("ssc-control-plane-configure-public-access",payload.deploymentId,"Production public verification");if(access?.publiclyReachable!==true)return{result:"NODE_04_15_PUBLIC_ACCESS_BLOCKED",deploymentId:payload.deploymentId,status:access?.status??"HEALTH_CHECKING",publicAccess:access};return{result:"NODE_04_15_LIVE",deploymentId:payload.deploymentId,status:"LIVE",liveUrl:access.checkUrl,health,publicAccess:access}}if(health?.status==="FAILED")return{result:"NODE_04_15_FAILED",deploymentId:payload.deploymentId,status:"FAILED",health};await wait.for({seconds:HEALTH_RETRY_SECONDS})}}
 current=await deploymentSnapshot(payload.deploymentId);return{result:current.status==="LIVE"?"NODE_04_15_LIVE":current.status==="FAILED"?"NODE_04_15_FAILED":"NODE_04_15_WAITING",deploymentId:payload.deploymentId,status:current.status,buildStatus:current.build_status,providerDeploymentId:current.provider_deployment_id,errorCode:current.error_code};
}});
